apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-apigateway-configmap
data:
  REDIS_HOST: "redis"    # Connection string of Redis Service
  REDIS_PORT: "6379"
  Keycloak__BaseUrl: "http://keycloak:8080" # DNS name  of Keycloak
  Keycloak__Realm: "bankaccount" # DNS name  of Keycloak 
  Keycloak__ClientId: "accountmanagementclient" # DNS name  of Keycloak
  Keycloak__ClientSecret: "YzIafNYXUoPWh9i7xoIsvcqUWuyWX8US" # DNS name  of Keycloak
  Keycloak__Audience: "account" # DNS name  of Keycloak
  Keycloak__Authority: "https://demo.identityserver.io" # DNS name  of Keycloak
  APPLICATION_CONFIG: |-
    Koalesce:
      OpenApiVersion: 3.0.1
      Title: BankingApp DDD API Gateway
      SourceOpenApiUrls:
        - 'http://192.168.58.1:5263/swagger/v2/swagger.json'
      MergedOpenApiPath: /swagger/v2/apigateway.yaml
      ApiGatewayBaseUrl: 'http://localhost:5000'
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS : http://+:80
 