apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-identityserver-configmap
data:
   REDIS_HOST: "redis-service"       # Internal DNS name of your Redis Service
   KEYCLOAK_URL: "http://keycloak-service" # Internal URL of Keycloak
   MONGO_SERVER: "mongo-service"
   SEQ_SERVER_URL: "http://seq-service"
   ASPNETCORE_ENVIRONMENT: "Development"