apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-loanmanagement-configmap
data:
   POSTGRES_HOST: "postgres-service" # Internal DNS name of your Postgres Service
   REDIS_HOST: "redis-service"       # Internal DNS name of your Redis Service
   RABBITMQ_HOST: "rabbitmq-service" # Internal DNS name of your RabbitMQ Service
   KEYCLOAK_URL: "http://keycloak-service" # Internal URL of Keycloak
   ASPNETCORE_ENVIRONMENT: "Development"